### ISSUE TITLE
Navigation in version documentation not possible

### ISSUE THREAD

**Issue by menski** [camunda/camunda-platform-docs#1101]
# To reproduce

1. open the [documentation](https://docs.camunda.io)
2. select a version [other than latest](https://docs.camunda.io/docs/1.3/guides/)
3. click any link in the navigation (guide, components, apis & clients) except reference
4. the documentation again shows the latest version of the page, and not the selected one

# Impact

As a user I cannot use the normal navigation to reach the components page of an older version, i.e. https://docs.camunda.io/docs/1.3/components/

**Comment by pepopowitz** [comment]
Okay, I think I can explain what's going on here.

I think it's related to the work we've been doing to replace vague file names (ex: #1077, #1071, #1069). We've been changing doc-id's in the [current docs](https://github.com/camunda/camunda-platform-docs/pull/1071/files#diff-5a182bf7a2e62e00270c8b85d258a5be961142c486662437bc17674f56dca653L2) and [docusaurus.config navbar settings](https://github.com/camunda/camunda-platform-docs/pull/1071/files#diff-a038096cbdea434999e1dce5ab497212f1fe18204dde1a027ce3bdd663261a2aL67), but not [the older versions of those docs](https://github.com/camunda/camunda-platform-docs/blob/main/versioned_docs/version-1.3/components/overview.md?plain=1#L2). So there's a mismatch between the top nav doc IDs when viewing older versions. 

When browsing version 1.3, for example, the top nav item for the Self-Managed section is looking for doc ID `self-managed/about-self-managed`. But there _is_ no doc in version 1.3 with ID `self-managed/about-self-managed` -- that version's corresponding doc has ID `self-managed/overview`. So docusaurus, _I think_, is reverting to the one in the latest version, because it's the only one it can find.

A few things I'm looking into as resolution -- 

1. Docusaurus has [a type of navbar item named `docsVersion`](https://62c814ff3641af00082fe735--docusaurus-2.netlify.app/docs/next/api/themes/configuration#navbar-docs-version) that sounds like it might be intended for this scenario. I'm not sure how it works, especially if the ID changes across different versions, but I'm going to play with it to see if it's a good solution.
2. If that doesn't work, I think we might need to leave doc IDs consistent across old versions vs current. @christinaausley I'm curious if you have thoughts about this. I _think_ it'd be easier for us to revert the updated current doc IDs to what all the older versions use, but if that's not reasonable based on your work, I think we'll need to update all the _old_ doc IDs instead.

I'll let you know what I find out with the first option, though!!!!

**Comment by christinaausley** [comment]
After discussing with @pepopowitz via Slack, he's going to take a look at option #1. If this doesn't work, I'll plan to launch a PR for each version updating all of the old doc version IDs/implementing redirects.

**Comment by pepopowitz** [comment]
No good news to report regarding the `docsVersion` navbar item, unfortunately. The documentation left me hopeful that this was the answer we were looking for, but it is for a different use case. 

Basically, it is used to link to the "default" document for the currently browsed version. If I'm on any page within the 1.3 docs, a `docsVersion` navbar item links me to `/docs/1.3/guides/`; on any page for the current version it links me to `/docs/guides/`. It's a strange use-case, and one that I don't totally understand, [but it looks from this conversation like the maintainers don't understand the purpose of this item either](https://discord.com/channels/398180168688074762/867060369087922187/981915144789581874).

So, it looks like we are stuck with changing the doc IDs for old versions of all docs that appear in the top nav.

@christinaausley when you're in next week we can talk more about a plan, if you want help or to pair on this work!

**Comment by christinaausley** [comment]
All good @pepopowitz. The good news is I can clearly see in each PR which ids were changed. I'll begin launching PRs for each version this week and next week.
