### ISSUE TITLE
When navigating to Guides, I'm returned to the latest version of the documentation

### ISSUE THREAD

**Issue by menski** [camunda/camunda-platform-docs#1111]
## Steps to reproduce

1. Open the documentation
2. Select a version other then latest
3. Navigate to Components section 
4. Navigate to Guides section -> :zap: Documentation returns to latest version

![version-bug](https://user-images.githubusercontent.com/516296/182169011-17406f37-652f-42cd-96b3-9d9804272805.gif)

## Expected Behavior 

In step 4. I expect the documentation to stay in the selected version

## Hints

Might be related with #1101

**Comment by pepopowitz** [comment]
@christinaausley @akeller I'm not sure how much of this you'd investigated over the weekend, but if you hadn't looked into this issue yet, the cause is that in #1066 we changed the ID of the default guides page to `introduction-to-camunda-platform-8`. It makes sense that we didn't also change the ID of the older versions....but to fix this issue, we'll have to come up with an ID that can be used across all versions.

**Comment by christinaausley** [comment]
This makes sense. As far as the id name? Hmmmm -- simply `introduction-to-camunda` perhaps? Interested in what @akeller thinks once she's back in the office.

**Comment by akeller** [comment]
I'm good with this @christinaausley.

**Comment by akeller** [comment]
Did this get resolved?

**Comment by christinaausley** [comment]
I'm happy to launch a PR @pepopowitz but didn't want to duplicate work if you were already on it. Let me know as I'm happy to proceed with changes.

**Comment by pepopowitz** [comment]
I haven't done anything!!!
