### ISSUE TITLE
Bad wording "Implementing a Connector"

### ISSUE THREAD

**Issue by MaxTru** [camunda/camunda-platform-docs#1176]
**Page:** https://docs.camunda.io/docs/guides/implementing-connectors/

**Bug Description:** We currently have a guide on docs which is named `Implementing a Connector`. This guide explains how one can use and configure an out-of-the-box connector. The word `Implementing` is hence wrong.

**Expected Behavior:** Connectors Team proposes to rename this to `Using an out-of-the-box connector` or `Configuring an out-of-the-box connector`. The reason is that the `Implementation of a Connector` will in the future refer to developing a custom / own connector. (e.g., `Implementing a custom connector`). Please also refer to how we distinguish `custom connector` and `out-of-the-box connector` [on docs](https://docs.camunda.io/docs/components/integration-framework/introduction-to-connectors/).

**Comment by akeller** [comment]
@christinaausley, what are your thought here?

**Comment by christinaausley** [comment]
"The reason is that the Implementation of a Connector will in the future refer to developing a custom / own connector. (e.g., Implementing a custom connector). Please also refer to how we distinguish custom connector and out-of-the-box connector [on docs](https://docs.camunda.io/docs/components/integration-framework/introduction-to-connectors/)."

This makes sense -- I'm good with this! Happy to launch a PR if you'd like.

**Comment by akeller** [comment]
@christinaausley please launch one and add @MaxTru as a reviewer. This feels straightforward.

**Comment by akeller** [comment]
This is live - https://docs.camunda.io/docs/guides/configuring-out-of-the-box-connectors/

**Comment by christinaausley** [comment]
@MaxTru -- any issues with closing this?
