### ISSUE TITLE
Remove `/next/` from sitemap and link-checking

### ISSUE THREAD

**Issue by akeller** [camunda/camunda-platform-docs#1273]
The `/next/` docs are considered "under construction". We should remove them from the sitemap, and if necessary also exclude them from link-checking, as those artifacts presume content stability.

## Origin

> If we want to stop worrying about redirects for `/next/` docs, we need to update our link-checking steps to ignore URLs if they match a certain pattern. I _think_ we are looking for the previous option just to get to green, and then I should add an issue for me to exclude `/next/` URLs from link-checking in a follow-up.

_Originally posted by @pepopowitz in https://github.com/camunda/camunda-platform-docs/issues/1241#issuecomment-1248505776_

**Comment by akeller** [comment]
@pepopowitz We also determined that `/next/` was in the sitemap, or pieces of it. Should we modify this issue to include removing `/next/` from the sitemap, which should also remove it from link-checking?

**Comment by pepopowitz** [comment]
I think those are two different questions. 

#### Should we remove `/next/` docs from link-checking?

link-checking confirms that people/bots with old URLs are redirected. By removing `/next` from link-checking we're saying "we don't care if people/bots get redirected when things move". 

I think that's correct, because `/next/` is technically unstable and I don't think we should be concerned with people/robots getting lost. 

#### Should we remove `/next` from the sitemap? 

URLs in the sitemap support the ability to find the page in search. The presence in the sitemap doesn't _guarantee_ that it can be found, but it increased the likelihood. Removing `/next/` from the sitemap says "we don't care if the `/next/` docs are searchable". 

I _think_ that we _do_ want the `/next/` docs to be searchable....but I guess I don't have a strong feeling either way. I suspect that the people helped the most by the `/next/` docs being searchable are internal...though most updates come right before the release, so maybe that doesn't matter.

What do you think about that second question?

**Comment by akeller** [comment]
> What do you think about that second question?

I'm worried `/next/` and the current docs version are competing with each other SEO-wise. The content is too similar and may get deindexed. `/next/` should be available for internal searching, but anyone coming into docs externally should come into the latest numbered version and navigate to older number versions for `/next/` manually.

**Comment by pepopowitz** [comment]
That makes sense. I'm convinced; I'll update the body of this issue.

**Comment by akeller** [comment]
`ignorePatterns` doesn't look like it worked... 😢 

I also realized I made a typo and added the same version twice. Oops! Will correct this in a PR shortly.

I'm able to do `npm run build` then `npm run serve` and I can see a sitemap generated locally (!!!). I was a little surprised given the [docs](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap) say it's only active in production until I realized build and serve DO set us up for production 😎 

At one point, there was a `cacheTime` parameter, but it's commented out, and I don't see anything about it in the current docs. I will remove this in a PR since it's taunting me.

Now the good news! 

Testing locally, I can see the sitemap DOES change if I add `/docs/` to each pattern, which I was surprised to see did exactly what I hoped for. So I'll make a PR for this. `ignorePatterns` does work, we just need to follow the right format for our doc URLs.

**Comment by pepopowitz** [comment]
> I did notice this was closed, but I did not do anything with link-checking (at least not intentionally). [Linkcheck.yaml](https://github.com/camunda/camunda-platform-docs/blob/main/.github/workflows/linkcheck.yaml) curls the prod sitemap, which we did remove /next/ from.
>
> Is there something else I'm missing, or is this closed and complete?

If `next` URLs are removed from the sitemap, they're no longer link-checked, so I think this is complete!
