### ISSUE TITLE
Prevent merge with label `hold`

### ISSUE THREAD

**Issue by tmetzke** [camunda/camunda-platform-docs#1526]
__What is the issue?__

Using the `hold` label is supposed to prevent merges of PRs until they are ready.
However, this is not enforced in any way and easy to overlook, Accidental merges can still easily happen.

__What should we do?__

Prevent merges of PRs with the label `hold`.

__Notes__

* We could create a workflow based on this action: https://github.com/marketplace/actions/enforce-pr-labels
* We define the `hold` label as a BANNED label, so the check will fail when it's set
* We define in branch protection rules that the check needs to pass to allow a merge

**Comment by pepopowitz** [comment]
I think this sounds great. I'm lacking context, so a couple questions: 

1. Did we have a PR merged with a `hold` label that shouldn't have been? 

2. From this statement...

   > the `hold` label is supposed to prevent merges of PRs

   by what guidelines is this supposed to be the case? Is this an expectation that's documented in this repo, or somewhere else? Is it undocumented, but an expectation based on experience in other projects? I'm just wondering if there's some broader set of guidelines we aren't following at all, because we don't know it exists.

**Comment by tmetzke** [comment]
1. Not that I am aware of but I just onboarded one person on our team and received the question why we don't enforce this technically.
2. The issue description says "This issue is parked, do not merge.". I would count that as documented.

I would actually like to establish something like this for all repositories where it makes sense (documentation and web modeler from the top of my head but probably also others). Repositories that lead to public content once PRs are merged and rather soon also released due to continuous delivery.

**Comment by akeller** [comment]
> I would actually like to establish something like this for all repositories 

+1 to this for consistency. I would support being early adopters of this in the docs repo since we do see `hold` PRs from time to time. 

I'll let you two continue to work out the implementation details.

**Comment by pepopowitz** [comment]
Assigning myself, and moving this issue to "Ready" as it seems like a nice small thing I can do while waiting for Google on https://github.com/camunda/product-hub/issues/232.
