### ISSUE TITLE
Incorporate appropriate video content into getting started guides

### ISSUE THREAD

**Issue by christinaausley** [camunda/camunda-platform-docs#1569]
According to @tstegemann, @HanselIdes proposed to have these three videos:

API Endpoints: https://vimeo.com/762692362/025d801c73
Microservices: https://vimeo.com/762694985/07220e785a
Human Task Orchestration: https://vimeo.com/762699004/e9a54ba396

linked in the corresponding “Getting started” guides in the docs:

https://docs.camunda.io/docs/guides/orchestrate-api-endpoints/
https://docs.camunda.io/docs/guides/orchestrate-microservices/
https://docs.camunda.io/docs/guides/orchestrate-human-tasks/

Before adding additional resources to the next steps section in these docs, I wanted to discuss the number of links in these sections (including a 2-hour link to the [Academy video content on HTO](https://docs.camunda.io/docs/next/guides/orchestrate-human-tasks/#additional-resources-and-next-steps)) to refactor these sections and add the video links, but also properly introduce why we may have two videos per guide, one short and one quite lengthy.

@HanselIdes Can you clarify the key differences between the existing videos and the proposed videos so we can note this appropriately or maintain just one over another? I want to ensure it's clear to users what additional resources they're clicking on and why.

**Comment by HanselIdes** [comment]
Hi @christinaausley,

The goal of the new videos is to provide an alternative medium for the same content (with some additional narrative and business context) and replace the weekly webinars we held.
The Academy videos go into more detail and would be considered an 'intermediate' version.

I imagined adding a line like
"Click here to follow along in video format" in the introductory section rather than in the list of links at the bottom.

I would like to measure their effectiveness (e.g. the number of people that view them), and the docs felt like a logical place to put links. I'm happy to

**Sidenote**
Looking over the video, we should have them up for about 1 month in an 'experimental' state before we consider pulling them down. The product UX is changing rapidly, so they have a shorter expiration date.

**Comment by christinaausley** [comment]
@HanselIdes thanks for elaborating here. So at large, the differences are beginner versus intermediate content?

Is there someone from your team who would manage this experiment to track success and effectiveness I should pair with?

**Comment by HanselIdes** [comment]
@christinaausley Yep, it's beginner vs intermediate content. And it's without registration vs with registration (via Camunda Academy)

I can work with you to track the experiment, and I linked the experimental issue above

**Comment by christinaausley** [comment]
See https://github.com/camunda/product-hub/issues/778 for additional discussion.

**Comment by akeller** [comment]
Tracked experiment is closed, so I'll close this too.
