### ISSUE TITLE
Add java code example to message correlation guide

### ISSUE THREAD

**Issue by Hafflgav** [camunda/camunda-platform-docs#1668]
Hey there 👋 
I wanted to discuss with you whether it makes sense to include a Java code example in the [message correlation guide](https://docs.camunda.io/docs/guides/message-correlation/) which makes use of the Spring-Zeebe dependency. 
Especially in the context of lectures it often happened to me that the students weren't familiar with node.js, hence I need to show a small example to make them understand how to actually do this. 

Maybe Docusaurus features the possibility to have a code-box where you can switch between different languages?  
I am happy to create a PR for this if you find this useful. :) 

Ty! 
Thomas

**Comment by Hafflgav** [comment]
(p.s. I cannot assign anyone so I just bother you @akeller & @christinaausley)

**Comment by akeller** [comment]
Hi @Hafflgav, since Spring-Zeebe is not officially supported, I'm hesitant to include it as part of a guide. This has been an ongoing conversation, specifically with Spring-Zeebe, which is why you may see it in other areas of the docs as a compromise.

@jwulf wrote this guide originally. Maybe he has some thoughts on this? 

Adding a switch between different languages is something we've considered for other areas of our docs, but we'll likely start in the APIs & Clients section first as an experiment since it will add additional maintenance overhead for the team.

**Comment by Hafflgav** [comment]
Thanks for the fast reply @akeller! 
Then I will keep the example in my personal c8-example repository. 
(I thought it might be useful to add a spring example since this is most probably the go-to language of our community) 

Lmk if your opinion changes on this topic or you find a better place for such an example to life in. I am happy to get it done. :) 

Have a great week! 
Thomas
