### ISSUE TITLE
Mention Operate OpenSearch Tag

### ISSUE THREAD

**Issue by ManuelDittmar** [camunda/camunda-platform-docs#2405]
We officially support OpenSearch and Elasticsearch. Based on this section https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/#elasticsearch-or-opensearch the user could get the impression, that configuration works the same, no matter if you use OpenSearch or Elasticsearch.

For OpenSearch however, a dedicated image needs to be used https://hub.docker.com/r/camunda/operate/tags

**Comment by akeller** [comment]
@johanwelgemoed Is this a quick fix or is there an open issue to address this?

**Comment by johanwelgemoed** [comment]
@akeller It should be a quick fix because as I understand it, the configuration stays the same, but I will confirm. As Manuel pointed out, we perhaps just need to add that they need a separate image from dockerHub. We don't have an issue open for this yet so I will just add this to our board and link any docs PRs to this.
