### ISSUE TITLE
Fix name of camunda helm charts on the upgrade page

### ISSUE THREAD

**Issue by upgradingdave** [camunda/camunda-platform-docs#2423]
Hey all, found a small glitch on this page here: 

https://docs.camunda.io/docs/next/self-managed/platform-deployment/helm-kubernetes/upgrade/

Under the `secrets extraction` section, the `helm upgrade ...` command should be changed from this: 

```
helm upgrade <RELEASE_NAME> charts/camunda-platform/ \
```

to this: 

```
helm upgrade <RELEASE_NAME> camunda/camunda-platform \
```

![Screen Shot 2023-08-09 at 5 03 26 PM](https://github.com/camunda/camunda-platform-docs/assets/939229/97efb1a9-a886-4e05-b4b7-42f980a235e7)

**Comment by akeller** [comment]
@camunda/distribution can you confirm?

**Comment by jessesimpson36** [comment]
Confirmed. This is indeed a typo in the docs. 

If you clone the camunda-platform-helm repository, it's "technically correct" because that chart name could refer to a directory path  or a  name of the chart, as it exists in the repository.   But we expect users to be using charts from our registry rather than cloning our git repository. 

So the correct value  is `camunda/camunda-platform`

**Comment by akeller** [comment]
@jessesimpson36 thank you for this context!
