### ISSUE TITLE
Mark pages / adjust content of pages that are directly linked from C7 docs

### ISSUE THREAD

**Issue by toco-cam** [camunda/camunda-platform-docs#941]
Consider direct links from C7 docs pointing to C8 docs for certain components:
- https://docs.camunda.io/docs/components/modeler/bpmn/
- https://docs.camunda.io/docs/components/optimize/what-is-optimize/

**Comment by christinaausley** [comment]
I think so long as links are disclaimed as a "hey, this is going to take you to C8 content" to avoid confusion between the doc sets this would be fine. For example, "For more information on Optimize as it relates to Camunda Platform 8, visit our [Camunda Platform 8 Optimize documentation](https://docs.camunda.io/docs/components/optimize/what-is-optimize/).

As @toco-cam opened the issue, I am curious about the motivation. Was this issue created because we are working to encourage our C7 users to see how the same components can work in C8? Have we had confusion among users between C7 and C8 docs? Why certain components over others? Just curious.

**Comment by akeller** [comment]
@toco-cam following up here - can you respond to @christinaausley's questions? This will help us prioritize this work.

**Comment by christinaausley** [comment]
Closing as stale, need context to revive.

**Comment by toco-cam** [comment]
@christinaausley / @akeller excuse - I missed this "Oct 3, 2022" i was living in JIRA world

**Comment by christinaausley** [comment]
@toco-cam No problem 😄 Happy to reopen -- do you see this as urgent? If not, will keep in the backlog and circle back once capacity opens up 👍
